spring:
  application:
    name: resource-server
    
  profiles:
    active: dev
    
---

spring:
  config:
    activate:
      on-profile: dev
      
rsa:
  public-key:
    path: keys/cosc411/authorization-server/prod/public.key
    
---

spring:
  config:
    activate:
      on-profile: test
      
rsa:
  public-key:
    path: keys/cosc411/authorization-server/test/public.key
